name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarQubeScan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=shippingservice
            -Dsonar.organization=tspbootcamp
            -Dsonar.host.url=http://16.52.52.212:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
